#!/bin/sh
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

function echo_error {
    echo "${RED}[gravy] $1${NC}"
}

function echo_warn {
    echo "${YELLOW}[gravy] $1${NC}"
}

function echo_info {
    echo "${GREEN}[gravy]${NC} $1"
}
